# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project_login_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project_login_1
	pod 'FirebaseUI'
	pod 'FirebaseAuthUI'
	pod 'Firebase'
	pod 'FirebaseUI/Email'

end
